Feature/populate
kptm-tools/core-service pull request #11
Opened 2024-12-04 09:20 UTC by cristianoCatolico

It populates tenants table reading from kickstart copy in core service and also validates tenantId and UserID in the token with fusionAuth.

2024-12-04 21:07 UTC, grez-lucas requested changes
Please fix unexpected behaviors on auth JWT decoding, and parsing the `kickstart` file multiple times. Don't worry about integrating the `FusionAuth Go Client` package yet (unless you wish to and feel it might help speed things up.) Lets keep things functional.

For formatting and linting, I suggest using the [VSCODE Official Go Extension](https://code.visualstudio.com/docs/languages/go).

Alternatively, you can use the `Makefile` in our repository root and use: 
- `make run`

2024-12-04 21:07 UTC, grez-lucas commented on pkg/api/auth.go
> +				fmt.Errorf("Invalid request build")
`fmt.Errorf()` is a function that creates a custom Go Error with the message you provided, in this case I suggest returning the error message as a:

 `return WriteJSON(w, http.StatusInternalServerError, APIError{ Error: err.Error() }` 

to handle  the case were building the FusionAuthVerifyRequest did not work.

2024-12-04 21:07 UTC, grez-lucas commented on pkg/api/auth.go
While this approach (validating with a client that connects to fusionAuth) works (and its OK!), I tried something similar on my Login service approach to perform requests to FusionAuth and ended up switching to the [FusionAuth Go Client](https://github.com/FusionAuth/go-client) package to handle responses in a cleaner way. I suggest we add a task to refactor this section of the code to use that package after this sprint.

2024-12-04 21:07 UTC, grez-lucas commented on pkg/utils/populate.go
> +func buildFusionAuthGetTenantsRequest() (*http.Request, error) {
I don't think this method is used anywhere in the codebase. Lets **get rid of it for now**, since it can be replaced with the [FusionAuth Go Client](https://github.com/FusionAuth/go-client) `client.RetrieveTenants` method if we wish to integrate it somewhere.

2024-12-04 21:07 UTC, grez-lucas commented on pkg/utils/parser.go
Great work with this parser!

2024-12-04 21:07 UTC, grez-lucas commented on pkg/utils/populate.go
> +	jsonFile, err := os.Open(dir + "/pkg/utils/fusionauth/kickstart/kickstart.json")
Wouldn't we want to open the parent repository kickstart json file?

2024-12-04 21:07 UTC, grez-lucas commented on pkg/utils/fusionauth/kickstart/kickstart.json
While this is **OK** **for testing**, it involves duplicating our already existing `kickstart.json` file from the [Parent Repository](https://github.com/kptm-tools/kptm-pentest/tree/dev/utils/fusionauth/kickstart). 

A cleaner approach would be to reference that instead in our parser, but I see difficulties in a Dockerized environment...

Lets **discuss this tomorrow**.

2024-12-04 21:07 UTC, grez-lucas commented on cmd/main.go
> +	result, err := utils.OpenAndReadKickstartJson(tenantService)
This leads to behavior where each time `core-service` restarts, the JSON file is re-opened, parsed and the db is re-populated. I suggest you integrate this `OpenAndReadKickstartJson` method in some way that allows it to run only when our core-service DB is first created and configured. (Maybe `storage/storage.go` is the best place for this).

![image](https://github.com/user-attachments/assets/460b32e3-41b4-4d0d-8cda-b44bfc56a029)

2024-12-04 21:07 UTC, grez-lucas commented on pkg/api/auth.go
> +				iss := "https://piedpipervideochat.com" // TODO: Set this to env var
Lets keep this issuer claim verification hardcoded to "https://app.kriptome.com" for now, which is what our **blueprint application** will use.

2024-12-04 21:07 UTC, grez-lucas commented on pkg/api/auth.go
>  			if err != nil {
Missing return statement after this WriteJSON call, which leads to this funny behavior (lol):

![image](https://github.com/user-attachments/assets/e3025cbc-f592-48ce-83d7-a9bb5188b554)

2024-12-04 21:07 UTC, grez-lucas commented on pkg/storage/tenant.go
Nice work!

2024-12-04 23:30 UTC, cristianoCatolico commented on pkg/utils/populate.go
> +func buildFusionAuthGetTenantsRequest() (*http.Request, error) {
Ok I remove

2024-12-04 23:39 UTC, cristianoCatolico commented on pkg/api/auth.go
> +				iss := "https://piedpipervideochat.com" // TODO: Set this to env var
Ok I change

2024-12-04 23:39 UTC, cristianoCatolico commented on pkg/storage/tenant.go
Thanks

2024-12-04 23:40 UTC, cristianoCatolico commented on pkg/utils/parser.go
Thanks

2024-12-04 23:47 UTC, cristianoCatolico commented on pkg/api/auth.go
> +				fmt.Errorf("Invalid request build")
I see thanks for the explanation

2024-12-04 23:56 UTC, cristianoCatolico commented on pkg/utils/populate.go
> +	jsonFile, err := os.Open(dir + "/pkg/utils/fusionauth/kickstart/kickstart.json")
Yes, I will try to be the parent directory

2024-12-05 02:48 UTC, cristianoCatolico commented on pkg/api/auth.go
I agree with you

2024-12-05 03:45 UTC, cristianoCatolico commented on cmd/main.go
> +	result, err := utils.OpenAndReadKickstartJson(tenantService)
I have create function to verify if exist in order to avoid duplication with tenantID

2024-12-05 03:46 UTC, cristianoCatolico commented on pkg/api/auth.go
>  			if err != nil {
Ok got it, thanks Lucas

2024-12-05 03:47 UTC, cristianoCatolico commented on pkg/utils/fusionauth/kickstart/kickstart.json
I like also the cleaner approach. I willy to have it.

2024-12-05 16:05 UTC, grez-lucas approved these changes

2024-12-05 16:05 UTC, merged